drop table if exists Hospital CASCADE;
drop table if exists Bed_Contain CASCADE;
drop table if exists Staff_Employee CASCADE;
drop table if exists Doctor_Employee CASCADE;
drop table if exists Nurse_Employee CASCADE;
drop table if exists Nurse_Supervise CASCADE;
drop table if exists Patient CASCADE;
drop table if exists Guardian CASCADE;
drop table if exists Health_Record CASCADE;
drop table if exists Insurance CASCADE;
drop table if exists Coverage CASCADE;
drop table if exists Assign CASCADE;
drop table if exists Shift CASCADE;
drop table if exists Take_Care CASCADE;
drop table if exists Test_Order CASCADE;
drop table if exists Test_Lab CASCADE;

SET datestyle = ymd;
show datestyle;

CREATE TABLE Hospital(
    hospital_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    address VARCHAR(60) NOT NULL UNIQUE,
    name VARCHAR(60) NOT NULL UNIQUE,
    tel VARCHAR(60) NOT NULL UNIQUE,
    capacity INT NOT NULL
);
GRANT SELECT ON Hospital TO public;

CREATE TABLE Health_Record(
    health_record_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    drug_taken VARCHAR(50),
    food_allergy VARCHAR(50)
);
GRANT SELECT ON Health_Record TO public;

CREATE TABLE Guardian(
    contact_info VARCHAR(40) NOT NULL,
    name VARCHAR(40) NOT NULL,
    relationship VARCHAR(20),
    PRIMARY KEY (contact_info, name)
);
GRANT SELECT ON Guardian TO public;

CREATE TABLE Coverage(
    insurance_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    amount REAL
);
GRANT SELECT ON COVERAGE TO PUBLIC;

CREATE TABLE Bed_Contain(
    hospital_id  INT NOT NULL,
    bed_num INT NOT NULL,
    building VARCHAR(30) NOT NULL,
    PRIMARY KEY (hospital_id, building, bed_num),
    FOREIGN KEY (hospital_id) REFERENCES Hospital(hospital_id) ON DELETE CASCADE ON UPDATE CASCADE
);
GRANT SELECT ON Bed_Contain TO public;

CREATE TABLE Staff_Employee(
    hospital_id INT NOT NULL,
    employee_id INT NOT NULL,
    name VARCHAR(60) NOT NULL,
    pager VARCHAR(60),
    start_date DATE NOT NULL,
    PRIMARY KEY (hospital_id, employee_id),
    FOREIGN KEY (hospital_id) REFERENCES Hospital(hospital_id) ON DELETE CASCADE ON UPDATE CASCADE
);
GRANT SELECT ON Staff_Employee TO public;

CREATE TABLE Doctor_Employee(
    hospital_id INT NOT NULL,
    doctor_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    specialization VARCHAR(40),
    PRIMARY KEY (hospital_id, doctor_id),
    FOREIGN KEY (hospital_id, doctor_id) REFERENCES Staff_Employee(hospital_id, employee_id) ON DELETE CASCADE ON UPDATE CASCADE
);
GRANT SELECT ON Doctor_Employee TO public;

CREATE TABLE Nurse_Employee(
    hospital_id INT NOT NULL,
    nurse_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (hospital_id, nurse_id),
    FOREIGN KEY (hospital_id, nurse_id) REFERENCES Staff_Employee(hospital_id, employee_id) ON DELETE CASCADE ON UPDATE CASCADE
);
GRANT SELECT ON Nurse_Employee TO public;

CREATE TABLE Nurse_Supervise(
    hospital_id INT NOT NULL,
    supervisee_id INT NOT NULL,
    supervisor_id INT NOT NULL,
    PRIMARY KEY (hospital_id, supervisee_id),
    FOREIGN KEY (hospital_id, supervisee_id) REFERENCES Nurse_Employee(hospital_id, nurse_id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (hospital_id, supervisor_id) REFERENCES Nurse_Employee(hospital_id, nurse_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
GRANT SELECT ON Nurse_Supervise TO public;

CREATE TABLE Patient(
    patient_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hospital_id INT NOT NULL,
    doctor_id INT NOT NULL,
    building VARCHAR(30) NOT NULL,
    bed_num INT NOT NULL,
    health_record_id INT NOT NULL UNIQUE,
    is_alive BOOLEAN,
    name VARCHAR(60),
    birthday DATE,
    sex BOOLEAN,
    height REAL,
    weight REAL,
    address VARCHAR(60),
    designate_start_date DATE,
    occupy_start_date DATE,
    UNIQUE (hospital_id,building, bed_num),
    FOREIGN KEY (hospital_id, doctor_id) REFERENCES Doctor_Employee(hospital_id, doctor_id)
        ON DELETE SET NULL ON UPDATE CASCADE ,
    FOREIGN KEY (health_record_id) REFERENCES Health_Record(health_record_id) ON DELETE SET NULL ON UPDATE CASCADE ,
    FOREIGN KEY (hospital_id, building, bed_num) REFERENCES Bed_Contain(hospital_id, building, bed_num)
        ON DELETE SET NULL ON UPDATE CASCADE
);
GRANT SELECT ON Patient TO public;

CREATE TABLE Shift(
    start_shift_time TIME PRIMARY KEY,
    shift_duration INTEGER
);
GRANT SELECT ON Shift TO public;

CREATE TABLE Insurance(
    insurance_id INT NOT NULL,
    patient_id INT NOT NULL,
    expiration_date DATE,
    PRIMARY KEY (patient_id, insurance_id),
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id)
      ON DELETE CASCADE ON UPDATE CASCADE ,
    FOREIGN KEY (insurance_id) REFERENCES Coverage(insurance_id)
);
GRANT SELECT ON Insurance TO public;

CREATE TABLE Assign(
    patient_id INT NOT NULL,
    hospital_id INT NOT NULL,
    nurse_ID INT NOT NULL,
    start_shift_time TIME,
    PRIMARY KEY (patient_id, hospital_id, nurse_id),
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id) ON DELETE CASCADE ON UPDATE CASCADE ,
    FOREIGN KEY (hospital_id, nurse_id) REFERENCES Nurse_Employee(hospital_id, nurse_id) ON DELETE CASCADE ON UPDATE CASCADE ,
    FOREIGN KEY (start_shift_time) REFERENCES Shift(start_shift_time) ON DELETE SET NULL ON UPDATE CASCADE
);
GRANT SELECT ON Assign TO public;

CREATE TABLE Take_Care(
    patient_id INT NOT NULL,
    contact_info VARCHAR(40),
    name VARCHAR(60),
    PRIMARY KEY (patient_id, contact_info, name),
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id)
      ON DELETE SET NULL ON UPDATE CASCADE ,
    FOREIGN KEY (contact_info, name) REFERENCES Guardian(contact_info, name)
      ON DELETE SET NULL ON UPDATE CASCADE
);
GRANT SELECT ON Take_Care TO public;

create table Test_Lab(
    test_lab_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(30) NOT NULL,
    test_method VARCHAR(20) NOT NULL
);
GRANT SELECT on test_lab to PUBLIC;

CREATE TABLE Test_Order(
    test_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    patient_id INT NOT NULL,
    hospital_id INT NOT NULL,
    doctor_id INT NOT NULL,
    positive BOOLEAN,
    test_date DATE,
    test_lab_id INT,
    FOREIGN KEY (test_lab_id) REFERENCES Test_Lab(test_lab_id),
    FOREIGN KEY (hospital_id, doctor_id) REFERENCES Doctor_Employee(hospital_id, doctor_id) ON DELETE SET NULL ON UPDATE CASCADE ,
    FOREIGN KEY (patient_id) REFERENCES Patient(patient_id)
       ON DELETE SET NULL ON UPDATE CASCADE
);
GRANT SELECT ON Test_Order TO public;
